version: '3'
services:
    php:
        build:
            context: .
            dockerfile: ./Dockerfile_dev
        command: php-fpm
        depends_on:
            - mysql
        ports:
            - 9000:9000
        volumes:
            - ./:/app:cached
            - /app/var/
        environment:
            PHP_IDE_CONFIG: "serverName=app.localhost"

    nginx:
        build:
            context: ./docker/nginx/
        depends_on:
            - php
        ports:
            - 8000:80
        volumes:
            - ./:/app:cached
            - /app/var/

    mysql:
        build:
            context: ./docker/mysql/
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3310:3306
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
